# Generated by Django 5.0.4 on 2024-06-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='Phone_numer',
            field=models.CharField(max_length=15),
        ),
    ]
